Repository cosmoscout/cosmoscout-vr, pull requests merged in 2019-09, with the labels that each got.

#40 Feature/vista docs
  docs/configuring.md
Labels: documentation

#45 :tada: Add code of conduct
  docs/README.md
  docs/changelog.md
  docs/code_of_conduct.md
Labels: documentation

#44 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#43 Feature/better build scripts
  .travis.yml
  README.md
  docs/install.md
  make_debug.bat
  make_debug.sh
  make_externals.bat
  make_externals.sh
  make_release.bat
  make_release.sh
Labels: enhancement

#52 Feature/changelog v1.1.0
  docs/changelog.md
Labels: documentation

#53 Feature/fix line ending issue
  resources/gui/calendar.html
  resources/gui/deletable_mark.html
  resources/gui/header.html
  resources/gui/logo.html
  resources/gui/sidebar.html
  resources/gui/statistics.html
  src/cs-utils/utils.cpp
  src/cs-utils/utils.hpp
Labels: bug

#55 :tada: Support double and multi click events on gui elements
  src/cs-gui/WebView.cpp
  src/cs-gui/WebView.hpp
Labels: enhancement

#59 Feature/coordinate systems doc
  docs/README.md
  docs/architecture.md
  docs/coordinate-systems.md
  docs/dependencies.md
  docs/img/coordinate-systems.jpg
  docs/install.md
  docs/release-management.md
Labels: documentation
