Repository cosmoscout/cosmoscout-vr, pull requests merged in 2023-11, with the labels that each got.

#362 Node Editor Improvements
  plugins/csl-node-editor/gui/csl-node-editor.html
  plugins/csl-node-editor/src/Node.hpp
  plugins/csl-node-editor/src/NodeEditor.cpp
  plugins/csl-node-editor/src/NodeFactory.cpp
  plugins/csl-node-editor/src/NodeFactory.hpp
  plugins/csp-demo-node-editor/CMakeLists.txt
  plugins/csp-demo-node-editor/src/Plugin.cpp
  plugins/csp-demo-node-editor/src/controls/TextDisplayControl.js
  plugins/csp-demo-node-editor/src/nodes/DisplayNode.js
  plugins/csp-demo-node-editor/src/nodes/TimeNode.cpp
  plugins/csp-demo-node-editor/src/nodes/TimeNode.hpp
  plugins/csp-demo-node-editor/src/nodes/TimeNode.js
Labels: new feature

#363 Fix fixed Sun direction after scene loading
  docs/changelog.md
  src/cs-core/SolarSystem.cpp
Labels: bug

#364 Add difference node to the node editor
  plugins/csl-ogc/src/common/utils.hpp
  plugins/csp-visual-query/src/Plugin.cpp
  plugins/csp-visual-query/src/operation-nodes/DifferenceImage2D/DifferenceImage2D.cpp
  plugins/csp-visual-query/src/operation-nodes/DifferenceImage2D/DifferenceImage2D.hpp
  plugins/csp-visual-query/src/operation-nodes/DifferenceImage2D/DifferenceImage2D.js
  src/cs-utils/utils.hpp
Labels: new feature, csp-visual-query
